CREATE TABLE tickets (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    custom_message TEXT,
    date_created TIMESTAMP NOT NULL DEFAULT CURRENT_DATE,
    date_modified TIMESTAMP,
    location_id INTEGER NOT NULL REFERENCES locations(id)
);